# Generated by Django 5.1.5 on 2025-03-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Factorysale',
            new_name='Factorysale2',
        ),
        migrations.RenameModel(
            old_name='Invoice',
            new_name='Invoice2',
        ),
        migrations.RenameModel(
            old_name='InvoiceItem',
            new_name='InvoiceItem2',
        ),
        migrations.RenameModel(
            old_name='login',
            new_name='login2',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Product2',
        ),
        migrations.RenameModel(
            old_name='Production',
            new_name='Production2',
        ),
        migrations.RenameModel(
            old_name='ProductionHistory',
            new_name='ProductionHistory2',
        ),
        migrations.RenameModel(
            old_name='reg',
            new_name='reg2',
        ),
    ]
