# Generated by Django 5.1.5 on 2025-03-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_rename_factorysale_factorysale2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice2',
            name='accessory_required',
        ),
        migrations.RemoveField(
            model_name='invoiceitem2',
            name='accessory_name',
        ),
        migrations.AddField(
            model_name='invoice2',
            name='accessory_price',
            field=models.IntegerField(default=0),
        ),
    ]
