# Generated by Django 5.1.5 on 2025-03-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_remove_invoice2_accessory_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice2',
            name='e_way',
            field=models.IntegerField(default=0),
        ),
    ]
