# Generated by Django 5.1.5 on 2025-03-10 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_invoice2_e_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem2',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app2.product2'),
        ),
    ]
