# Generated by Django 5.1.5 on 2025-03-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_alter_invoiceitem2_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice2',
            name='sp_discount',
            field=models.IntegerField(default=0),
        ),
    ]
