# Generated by Django 5.1.5 on 2025-04-09 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_invoice2_sp_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice2',
            name='customer',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='invoice2',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app2.customer2'),
        ),
    ]
