# Generated by Django 5.1.5 on 2025-04-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_customer2_alter_invoice2_customer_invoice2_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice2',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice2',
            name='money_got',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
