# Generated by Django 5.1.5 on 2025-04-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_invoice2_balance_amount_invoice2_money_got'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice2',
            name='balance_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice2',
            name='money_got',
            field=models.IntegerField(default=0),
        ),
    ]
