# Generated by Django 5.1.5 on 2025-04-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_paymentrecord2'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice2',
            name='original_money_got',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
