# Generated by Django 5.1.5 on 2025-05-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0012_customer2_advance_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice2',
            name='original_money_got',
        ),
        migrations.AddField(
            model_name='invoice2',
            name='advance_used',
            field=models.IntegerField(default=0),
        ),
    ]
