# Generated by Django 5.1.5 on 2025-01-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.CharField(default='Unknown Customer', max_length=30),
        ),
    ]
