# Generated by Django 5.1.5 on 2025-02-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='accessory_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='accessory_required',
            field=models.BooleanField(default=False),
        ),
    ]
