# Generated by Django 5.1.5 on 2025-02-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_invoice_accessory_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='accessory_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
