# Generated by Django 5.1.5 on 2025-03-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_factorysale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='accessory_required',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='accessory_name',
        ),
        migrations.AddField(
            model_name='invoice',
            name='accessory_price',
            field=models.IntegerField(default=0),
        ),
    ]
