# Generated by Django 5.1.5 on 2025-03-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_invoice_accessory_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='e_way',
            field=models.IntegerField(default=0),
        ),
    ]
