# Generated by Django 5.1.5 on 2025-03-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_invoiceitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sp_discount',
            field=models.IntegerField(default=0),
        ),
    ]
