# Generated by Django 5.1.5 on 2025-05-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_customer_invoice_balance_amount_invoice_money_got_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='original_money_got',
        ),
        migrations.AddField(
            model_name='customer',
            name='advance_amount',
            field=models.IntegerField(default=0, help_text='Advance amount paid by the customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='advance_used',
            field=models.IntegerField(default=0),
        ),
    ]
